apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-deployment
  labels:
    app: java-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-k8s
  template:
    metadata:
      labels:
        app: java-k8s
    spec:
      terminationGracePeriodSeconds: 20
      volumes:
        - name: java-k8s-configmap-volume
          configMap:
            name: java-k8s-configmap
      containers:
        - name: java-k8s
          image: gcr.io/ultra-tube-309002/java-k8s
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          volumeMounts:
            - name: java-k8s-configmap-volume
              mountPath: "/config"
              readOnly: true
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "cloud"
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              hostPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-k8s-configmap
data:
  execution-environment: "Kubernetes"
  server.port: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: java-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: java-k8s
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
